# Generated by Django 4.2.10 on 2024-05-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0006_unidadesaude_logo'),
        ('saude_farmacia', '0002_insumo_quantidade_medicamento_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumorequisitado',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de saúde'),
        ),
        migrations.AddField(
            model_name='medicamentorequisitado',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de saúde'),
        ),
        migrations.AddField(
            model_name='produtorequisitado',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de saúde'),
        ),
    ]
