# Generated by Django 4.2.10 on 2024-08-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude_farmacia', '0003_insumorequisitado_unidade_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='codigo_de_barra',
            field=models.CharField(blank=True, error_messages={'unique': 'Um medicamento com esse código de barra já existe. '}, max_length=50, null=True, unique=True, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='estoque_minimo_geral',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estoque mínimo geral'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome_medicamento',
            field=models.CharField(blank=True, error_messages={'unique': 'Um medicamento com esse nome já existe.'}, max_length=200, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='principio_ativo_medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_farmacia.principioativo', verbose_name='Princípio ativo do medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo_medicamento',
            field=models.IntegerField(blank=True, choices=[(0, 'BÁSICO'), (1, 'ESPECIALIZADO'), (2, 'ESTRATÉGICO')], default=0, null=True),
        ),
    ]
