# Generated by Django 4.2.10 on 2024-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_farmacia', '0004_alter_medicamento_codigo_de_barra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome_medicamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
    ]
