# Generated by Django 4.2.10 on 2024-12-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_farmacia', '0005_alter_medicamento_nome_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='tipo_medicamento',
            field=models.IntegerField(blank=True, choices=[(0, 'COD SUS'), (1, 'LICITAÇÃO'), (2, 'AVULSO')], default=0, null=True),
        ),
    ]
