# Generated by Django 4.2.10 on 2025-02-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_farmacia', '0006_alter_medicamento_tipo_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
