# Generated by Django 4.2.10 on 2024-05-06 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saude', '0001_initial'),
        ('rh', '0001_initial'),
        ('comum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setorunidade',
            name='unidade_saude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de saúde'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='cargo_emprego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.cargoemprego'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcao'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='jornada_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.jornadatrabalho'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='nivel_escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.nivelescolaridade'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='pessoa_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='regime_juridico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.regimejuridico'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='rh.setorunidade', verbose_name='Setor em que está lotado'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor_exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servidores_exercicio', to='rh.setorunidade', verbose_name='Setor de Exercício'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.situacao', verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_pessoajuridica_uf_set', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cnh_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cnh_uf_set', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='ctps_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_ctps_uf_set', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='deficiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.deficiencia', verbose_name='Deficiência'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.estadocivil'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='nascimento_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='pagto_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='pais_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.pais', verbose_name='País de Origem'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='raca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.raca'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='rg_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_rg_uf_set', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='titulo_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_titulo_uf_set', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
