# Generated by Django 4.2.10 on 2024-05-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispb', models.CharField(max_length=8)),
                ('codigo', models.CharField(max_length=3)),
                ('nome_curto', models.CharField(max_length=70)),
                ('nome_longo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civis',
            },
        ),
        migrations.CreateModel(
            name='GrupoDeficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Grupo de Deficiência',
                'verbose_name_plural': 'Grupos de Deficiências',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=55, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('ibge', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=155)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.estado')),
            ],
            options={
                'verbose_name': 'Município',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('grupo_deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.grupodeficiencia', verbose_name='Grupo de Deficiência')),
            ],
            options={
                'verbose_name': 'Deficiência',
                'verbose_name_plural': 'Deficiências',
            },
        ),
    ]
