# Generated by Django 4.2.10 on 2024-05-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suporte',
            field=models.BooleanField(default=False, verbose_name='É Suporte?'),
        ),
    ]
