# Generated by Django 4.2.10 on 2024-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_usuario_suporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='deve_mudar_senha',
            field=models.BooleanField(default=False, verbose_name='Deve mudar a senha no próximo acesso'),
        ),
    ]
