# Generated by Django 4.2.10 on 2024-11-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_usuario_deve_mudar_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('caminho', models.CharField(max_length=200, verbose_name='Caminho')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de acesso',
                'verbose_name_plural': 'Registros de acesso',
                'ordering': ['-data_hora'],
            },
        ),
    ]
