# Generated by Django 4.2.10 on 2025-01-25 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0008_unidadesaude_cep_unidadesaude_endereco'),
        ('autenticacao', '0004_registroacesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelUnidadeUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='painel_unidade_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Painel')),
            ],
            options={
                'verbose_name': 'Painel Unidade Usuário',
                'verbose_name_plural': 'Paineis Unidade Usuário',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
