# Generated by Django 4.2.10 on 2024-05-06 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saude', '0002_initial'),
        ('saude_atendimento', '0001_initial'),
        ('saude_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaChamadaSolicitacaoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'EM ESPERA'), (2, 'DESIGNADO'), (3, 'TRANSFERÊNCIA'), (4, 'OBITO'), (5, 'EM ATENDIMENTO'), (6, 'CONCLUIDO'), (7, 'REVELIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('tipo', models.SmallIntegerField(blank=True, choices=[(0, 'EXAME LABORATÓRIO'), (1, 'EXAME IMAGEM'), (2, 'PROCEDIMENTO'), (3, 'MEDICAÇÃO')], default=0, null=True, verbose_name='Tipo')),
                ('sequencial', models.IntegerField(blank=True, null=True, verbose_name='Sequencial')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.atendimentomedico')),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sala_lista_chamada_enfermagem_set', to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'Lista de Chamado Solicitação',
                'verbose_name_plural': '2 - Lista de Chamados das Solicitações',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SolicitacaoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_atendimento', models.BigIntegerField(blank=True, null=True, verbose_name='Número Atendimento')),
                ('enfermeiros', models.ManyToManyField(blank=True, to='saude_cadastro.profissional')),
                ('lista_chamada_solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadasolicitacaoatendimento')),
            ],
            options={
                'verbose_name': 'Solicitação Atendimento',
                'verbose_name_plural': '3 - Solicitações dos Atendimentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SituacaoMedicacaoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_hora_aplicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da Aplicação')),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('medicacao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.medicacaoatendimento')),
            ],
            options={
                'verbose_name': 'Situação Medicação Atendimento',
                'verbose_name_plural': '1 - Situações das Medicações dos Atendimentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RequisicaoSolicitacaoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Solicitação Finalizado?')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.atendimentomedico')),
                ('listas_chamadas_solicitacoes', models.ManyToManyField(to='saude_enfermagem.listachamadasolicitacaoatendimento')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
            ],
            options={
                'verbose_name': 'Requisição da Solicitação',
                'verbose_name_plural': '3 - Requisições das Solicitações',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricoEsperaSolicitacoes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'EM ESPERA'), (2, 'DESIGNADO'), (3, 'TRANSFERÊNCIA'), (4, 'OBITO'), (5, 'EM ATENDIMENTO'), (6, 'CONCLUIDO'), (7, 'REVELIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('tempo_espera', models.DurationField(blank=True, null=True)),
                ('lista_chamada_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadasolicitacaoatendimento')),
            ],
            options={
                'verbose_name': 'Histórico de Tempo de Espera',
                'verbose_name_plural': 'Histórico de Tempo de Espera',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalListaChamadaSolicitacaoAtendimento',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'EM ESPERA'), (2, 'DESIGNADO'), (3, 'TRANSFERÊNCIA'), (4, 'OBITO'), (5, 'EM ATENDIMENTO'), (6, 'CONCLUIDO'), (7, 'REVELIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('tipo', models.SmallIntegerField(blank=True, choices=[(0, 'EXAME LABORATÓRIO'), (1, 'EXAME IMAGEM'), (2, 'PROCEDIMENTO'), (3, 'MEDICAÇÃO')], default=0, null=True, verbose_name='Tipo')),
                ('sequencial', models.IntegerField(blank=True, null=True, verbose_name='Sequencial')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atendimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_atendimento.atendimentomedico')),
                ('enfermeiro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.profissional')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'historical Lista de Chamado Solicitação',
                'verbose_name_plural': 'historical 2 - Lista de Chamados das Solicitações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
