# Generated by Django 4.2.10 on 2024-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_enfermagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacaomedicacaoatendimento',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado?'),
        ),
        migrations.AddField(
            model_name='situacaomedicacaoatendimento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
