# Generated by Django 4.2.10 on 2024-09-25 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import publicmanager.saude_enfermagem.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0003_profissional_cofen'),
        ('saude', '0006_unidadesaude_logo'),
        ('saude_atendimento', '0014_boletimpaciente_tipo_historicalboletimpaciente_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saude_farmacia', '0005_alter_medicamento_nome_medicamento'),
        ('saude_enfermagem', '0002_situacaomedicacaoatendimento_cancelado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracaoMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dosagem', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dosagem')),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma Farmaceutica')),
                ('admin_medicamentosa', models.SmallIntegerField(choices=[(0, 'ORAL'), (1, 'PARENTAL'), (2, 'SUBCUTÂNIA'), (3, 'NASAL'), (4, 'RETAL'), (5, 'INTRAVESICAL'), (6, 'NEBOLIZAÇÃO'), (7, 'OCULAR'), (8, 'SUBLINGUAL')], verbose_name='Via de Administação Medicamentosa')),
                ('tipo_parenteral', models.SmallIntegerField(blank=True, choices=[(0, 'INTRAVENOSA'), (1, 'INTRAMUSCULAR'), (2, 'SUBCUTÂNEA'), (3, 'INTRATECAL')], null=True, verbose_name='Tipo Parental')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('posologia', models.SmallIntegerField(blank=True, choices=[(0, 'DOSE UNICA'), (1, 'SEMANAL'), (2, 'MENSAL')], null=True, verbose_name='Posologia')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'Administração de Medicamento',
                'verbose_name_plural': '6 - Administração de Medicamentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ListaChamadoAdministracaoMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'DESIGNADO'), (2, 'EM ATENDIMENTO'), (3, 'EM ATENDIMENTO DE RETORNO'), (4, 'CONCLUIDO'), (5, 'OBITO'), (6, 'REVELIA'), (7, 'ENCERRADO PELA ENFERMAGEM'), (8, 'ENCERRADO PELA ALTA'), (9, 'ENCERRADO PELA RECEPÇÃO'), (10, 'ENCERRADO PELO SISTEMA'), (11, 'TRANSFERÊNCIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('boletim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.boletimpaciente', verbose_name='Boletim')),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'Lista de Chamado Administração Medicamento',
                'verbose_name_plural': '5 - Lista de Chamados Administrações de Medicamentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='solicitacaoatendimento',
            options={'verbose_name': 'Solicitação Atendimento', 'verbose_name_plural': '4 - SolicitReceitaMedicamentoações dos Atendimentos'},
        ),
        migrations.CreateModel(
            name='SituacaoAdministracaoMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_hora_aplicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da Aplicação')),
                ('situacao', models.SmallIntegerField(choices=[(0, 'SOLICITADO'), (1, 'APLICADO'), (2, 'CANCELADO')], default=0, verbose_name='Situação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('sequencial', models.IntegerField(blank=True, null=True, verbose_name='Sequencial')),
                ('administracao_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.administracaomedicamento')),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
            ],
            options={
                'verbose_name': 'Situação Administração Medicamento',
                'verbose_name_plural': '7 - Situações Administrações de Medicametos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceitaMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=publicmanager.saude_enfermagem.models.documentacao_administracao_medicamento_path, verbose_name='Arquivo')),
                ('foto_receita', models.ImageField(blank=True, null=True, upload_to=publicmanager.saude_enfermagem.models.documentacao_administracao_medicamento_foto_path)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('lista_chamada_solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadoadministracaomedicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.paciente')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'Receita Medicamento',
                'verbose_name_plural': '6 - Receitas do Medicamentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricoListaChamadoAdministracaoMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'DESIGNADO'), (2, 'EM ATENDIMENTO'), (3, 'EM ATENDIMENTO DE RETORNO'), (4, 'CONCLUIDO'), (5, 'OBITO'), (6, 'REVELIA'), (7, 'ENCERRADO PELA ENFERMAGEM'), (8, 'ENCERRADO PELA ALTA'), (9, 'ENCERRADO PELA RECEPÇÃO'), (10, 'ENCERRADO PELO SISTEMA'), (11, 'TRANSFERÊNCIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status')),
                ('tempo_espera', models.DurationField(blank=True, null=True)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('lista_chamado_administracao_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadoadministracaomedicamento')),
            ],
            options={
                'verbose_name': 'Histórico de Tempo de Espera do Atendimeto',
                'verbose_name_plural': 'Histórico de Tempo de Espera do Atendimeto',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalListaChamadoAdministracaoMedicamento',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'DESIGNADO'), (2, 'EM ATENDIMENTO'), (3, 'EM ATENDIMENTO DE RETORNO'), (4, 'CONCLUIDO'), (5, 'OBITO'), (6, 'REVELIA'), (7, 'ENCERRADO PELA ENFERMAGEM'), (8, 'ENCERRADO PELA ALTA'), (9, 'ENCERRADO PELA RECEPÇÃO'), (10, 'ENCERRADO PELO SISTEMA'), (11, 'TRANSFERÊNCIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('boletim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_atendimento.boletimpaciente', verbose_name='Boletim')),
                ('enfermeiro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.profissional')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'historical Lista de Chamado Administração Medicamento',
                'verbose_name_plural': 'historical 5 - Lista de Chamados Administrações de Medicamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='administracaomedicamento',
            name='receita_medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.receitamedicamento'),
        ),
    ]
