# Generated by Django 4.2.10 on 2024-10-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude_enfermagem', '0003_administracaomedicamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolistachamadoadministracaomedicamento',
            options={'verbose_name': 'Histórico de Administração de Medicamento', 'verbose_name_plural': 'Históricos de Administrações de Medicamentos'},
        ),
    ]
