# Generated by Django 4.2.10 on 2024-11-27 02:48

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0003_profissional_cofen'),
        ('saude_enfermagem', '0004_alter_historicolistachamadoadministracaomedicamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallistachamadasolicitacaoatendimento',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'EM ESPERA'), (2, 'DESIGNADO'), (3, 'TRANSFERÊNCIA'), (4, 'OBITO'), (5, 'EM ATENDIMENTO'), (6, 'CONCLUIDO'), (7, 'REVELIA'), (8, 'REABERTURA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='historicoesperasolicitacoes',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'EM ESPERA'), (2, 'DESIGNADO'), (3, 'TRANSFERÊNCIA'), (4, 'OBITO'), (5, 'EM ATENDIMENTO'), (6, 'CONCLUIDO'), (7, 'REVELIA'), (8, 'REABERTURA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='listachamadasolicitacaoatendimento',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'EM ESPERA'), (2, 'DESIGNADO'), (3, 'TRANSFERÊNCIA'), (4, 'OBITO'), (5, 'EM ATENDIMENTO'), (6, 'CONCLUIDO'), (7, 'REVELIA'), (8, 'REABERTURA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='ReaberturaSolicitacaoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='justificativa')),
                ('lista_chamada_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadasolicitacaoatendimento')),
                ('medico_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
            ],
            options={
                'verbose_name': 'Reabertura Solicitação Atendimento',
                'verbose_name_plural': 'Reaberturas das Solicitações dos Atendimentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
