# Generated by Django 4.2.10 on 2024-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_enfermagem', '0005_alter_historicallistachamadasolicitacaoatendimento_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracaomedicamento',
            name='posologia',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'DOSE UNICA'), (1, 'SEMANAL'), (2, 'MENSAL'), (3, 'DIARIA')], null=True, verbose_name='Posologia'),
        ),
    ]
