# Generated by Django 4.2.10 on 2024-12-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_enfermagem', '0006_alter_administracaomedicamento_posologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracaomedicamento',
            name='periodo',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'DOSE UNICA'), (1, 'SEMANAL'), (2, 'MENSAL'), (3, 'DIARIA')], null=True, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='situacaoadministracaomedicamento',
            name='aplicou_antes',
            field=models.BooleanField(default=False, verbose_name='Aplicou antes da hora?'),
        ),
        migrations.AddField(
            model_name='situacaoadministracaomedicamento',
            name='cancelou',
            field=models.BooleanField(default=False, verbose_name='Cancelou?'),
        ),
        migrations.AlterField(
            model_name='administracaomedicamento',
            name='posologia',
            field=models.CharField(blank=True, null=True, verbose_name='Posologia'),
        ),
    ]
