# Generated by Django 4.2.10 on 2025-02-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude_enfermagem', '0007_administracaomedicamento_periodo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoatendimento',
            options={'verbose_name': 'Solicitação Atendimento', 'verbose_name_plural': '4 - Solicitações dos Atendimentos'},
        ),
    ]
