# Generated by Django 4.2.10 on 2025-02-28 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import publicmanager.saude_enfermagem.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saude_cadastro', '0005_alter_unidadesetor_tipo'),
        ('saude_atendimento', '0025_classificacaorisco_tipo_fluxo_and_more'),
        ('saude', '0008_unidadesaude_cep_unidadesaude_endereco'),
        ('saude_enfermagem', '0008_alter_solicitacaoatendimento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracaoProcedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.procedimento')),
            ],
            options={
                'verbose_name': 'Administração de Procedimento',
                'verbose_name_plural': '10 - Administração de Procedimento',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ListaChamadoAdministracaoProcedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'DESIGNADO'), (2, 'EM ATENDIMENTO'), (3, 'EM ATENDIMENTO DE RETORNO'), (4, 'CONCLUIDO'), (5, 'OBITO'), (6, 'REVELIA'), (7, 'ENCERRADO PELA ENFERMAGEM'), (8, 'ENCERRADO PELA ALTA'), (9, 'ENCERRADO PELA RECEPÇÃO'), (10, 'ENCERRADO PELO SISTEMA'), (11, 'TRANSFERÊNCIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('classificacao_risco', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='classificacao_risco_lista_procedimento_set', to='saude_atendimento.classificacaorisco')),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'Lista de Chamado Administração Procedimento',
                'verbose_name_plural': '8 - Lista de Chamados Administrações de Procedimento',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SituacaoAdministracaoProcedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_hora_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da Execução')),
                ('situacao', models.SmallIntegerField(choices=[(0, 'SOLICITADO'), (1, 'REALIZADO'), (2, 'CANCELADO')], default=0, verbose_name='Situação')),
                ('sequencial', models.IntegerField(blank=True, null=True, verbose_name='Sequencial')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('cancelou', models.BooleanField(default=False, verbose_name='Cancelou?')),
                ('administracao_procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.administracaoprocedimento')),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
            ],
            options={
                'verbose_name': 'Situação Administração Procedimentos',
                'verbose_name_plural': '11 - Situações Administrações de Procedimentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceitaAdministracaoProcedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=publicmanager.saude_enfermagem.models.documentacao_administracao_procedimento_path, verbose_name='Arquivo')),
                ('foto_receita', models.ImageField(blank=True, null=True, upload_to=publicmanager.saude_enfermagem.models.documentacao_administracao_procedimento_foto_path)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('lista_chamada_solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadoadministracaoprocedimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.paciente')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'Receita Procedimento',
                'verbose_name_plural': '9 - Receitas do Procedimentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricoListaChamadoAdministracaoProcedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'DESIGNADO'), (2, 'EM ATENDIMENTO'), (3, 'EM ATENDIMENTO DE RETORNO'), (4, 'CONCLUIDO'), (5, 'OBITO'), (6, 'REVELIA'), (7, 'ENCERRADO PELA ENFERMAGEM'), (8, 'ENCERRADO PELA ALTA'), (9, 'ENCERRADO PELA RECEPÇÃO'), (10, 'ENCERRADO PELO SISTEMA'), (11, 'TRANSFERÊNCIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status')),
                ('tempo_espera', models.DurationField(blank=True, null=True)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('lista_chamado_administracao_procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.listachamadoadministracaoprocedimento')),
            ],
            options={
                'verbose_name': 'Histórico de Administração de Procedimentos',
                'verbose_name_plural': 'Históricos de Administrações de Procedimentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalListaChamadoAdministracaoProcedimento',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'DESIGNADO'), (2, 'EM ATENDIMENTO'), (3, 'EM ATENDIMENTO DE RETORNO'), (4, 'CONCLUIDO'), (5, 'OBITO'), (6, 'REVELIA'), (7, 'ENCERRADO PELA ENFERMAGEM'), (8, 'ENCERRADO PELA ALTA'), (9, 'ENCERRADO PELA RECEPÇÃO'), (10, 'ENCERRADO PELO SISTEMA'), (11, 'TRANSFERÊNCIA')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Situação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classificacao_risco', models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_atendimento.classificacaorisco')),
                ('enfermeiro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.profissional')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'historical Lista de Chamado Administração Procedimento',
                'verbose_name_plural': 'historical 8 - Lista de Chamados Administrações de Procedimento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='administracaoprocedimento',
            name='receita_procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_enfermagem.receitaadministracaoprocedimento'),
        ),
    ]
