# Generated by Django 4.2.10 on 2024-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exameatendimento',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='justificativa'),
        ),
        migrations.AlterField(
            model_name='exameatendimento',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'ANEXADO'), (2, 'SEM ANEXO')], default=0, null=True, verbose_name='Situação'),
        ),
    ]
