# Generated by Django 4.2.10 on 2024-05-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0002_alter_profissional_tipo_profissional'),
        ('saude_atendimento', '0003_exameatendimento_justificativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaorisco',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissional_classificacao_risco_set', to='saude_cadastro.profissional'),
        ),
        migrations.AddField(
            model_name='classificacaorisco',
            name='reclassificacao',
            field=models.BooleanField(default=False, verbose_name='Reclassificação?'),
        ),
        migrations.AddField(
            model_name='classificacaorisco',
            name='setor',
            field=models.SmallIntegerField(choices=[(0, 'TRIAGEM'), (1, 'ATENDIMENTO MÉDICO')], default=0, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='classificacaorisco',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ATIVO'), (1, 'DESABILITADO')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalclassificacaorisco',
            name='profissional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.profissional'),
        ),
        migrations.AddField(
            model_name='historicalclassificacaorisco',
            name='reclassificacao',
            field=models.BooleanField(default=False, verbose_name='Reclassificação?'),
        ),
        migrations.AddField(
            model_name='historicalclassificacaorisco',
            name='setor',
            field=models.SmallIntegerField(choices=[(0, 'TRIAGEM'), (1, 'ATENDIMENTO MÉDICO')], default=0, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='historicalclassificacaorisco',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ATIVO'), (1, 'DESABILITADO')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='medicacaoatendimento',
            name='dose_unica',
            field=models.BooleanField(default=True, verbose_name='Dose Única?'),
        ),
        migrations.AddField(
            model_name='medicacaoatendimento',
            name='tipo_posologia',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'HORAS'), (1, 'MINUTOS')], null=True, verbose_name='Tipo Posologia'),
        ),
        migrations.RemoveField(
            model_name='atendimentomedico',
            name='classificacao_risco',
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='boletim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletim_classificacao_risco_set', to='saude_atendimento.boletimpaciente', verbose_name='Boletim'),
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='temperatura'),
        ),
        migrations.AlterField(
            model_name='historicalclassificacaorisco',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='temperatura'),
        ),
        migrations.AlterField(
            model_name='medicacaoatendimento',
            name='dosagem',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dosagem'),
        ),
        migrations.AlterField(
            model_name='medicacaoatendimento',
            name='posologia',
            field=models.CharField(blank=True, null=True, verbose_name='Posologia'),
        ),
        migrations.AddField(
            model_name='atendimentomedico',
            name='classificacao_risco',
            field=models.ManyToManyField(blank=True, to='saude_atendimento.classificacaorisco'),
        ),
    ]
