# Generated by Django 4.2.10 on 2024-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0004_classificacaorisco_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicacaoatendimento',
            name='tipo_parenteral',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'INTRAVENOSA'), (1, 'INTRAMUSCULAR'), (2, 'SUBCUTÂNEA'), (3, 'INTRATECAL')], null=True, verbose_name='Tipo Parental'),
        ),
    ]
