# Generated by Django 4.2.10 on 2024-06-25 23:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('saude_atendimento', '0005_alter_medicacaoatendimento_tipo_parenteral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='bairro',
            field=models.CharField(blank=True, help_text='Nome do bairro', max_length=200, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, help_text='Nome do bairro', max_length=200, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.municipio'),
        ),
    ]
