# Generated by Django 4.2.10 on 2024-07-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('saude_atendimento', '0007_alter_historicalpaciente_grau_de_instrucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='bairro',
            field=models.CharField(blank=True, help_text='Nome do bairro', max_length=200, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='celular_responsavel_1',
            field=models.CharField(blank=True, help_text='Celular do Responsável 1', max_length=15, null=True, verbose_name='Celular do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='celular_responsavel_2',
            field=models.CharField(blank=True, help_text='Celular do Responsável 2', max_length=15, null=True, verbose_name='Celular do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=14, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento torre, sala etc', max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='cpf_responsavel_1',
            field=models.CharField(blank=True, help_text='CPF do Responsável 1', max_length=14, null=True, verbose_name='CPF do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='cpf_responsavel_2',
            field=models.CharField(blank=True, help_text='CPF do Responsável 1', max_length=14, null=True, verbose_name='CPF do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='email_responsavel_1',
            field=models.EmailField(blank=True, help_text='E-mail do Responsável 1', max_length=254, null=True, verbose_name='E-mail do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='email_responsavel_2',
            field=models.EmailField(blank=True, help_text='E-mail do Responsável 2', max_length=254, null=True, verbose_name='E-mail do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='endereco',
            field=models.CharField(blank=True, help_text='Nome da rua, travessa ou avenida', max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[['+', '+'], ['-', '-']], help_text='Fator RH', max_length=8, null=True, verbose_name='Fator RH'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[['A', 'A'], ['B', 'B'], ['AB', 'AB'], ['O', 'O']], help_text='Grupo Sanguíneo', max_length=2, null=True, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nacionalidade',
            field=models.CharField(blank=True, help_text='Naturalidade', max_length=255, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Naturalidade', max_length=255, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nome_mae',
            field=models.CharField(blank=True, help_text='Nome da mãe', max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nome_pai',
            field=models.CharField(blank=True, help_text='Nome do pai', max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nome_responsavel_1',
            field=models.CharField(blank=True, help_text='Nome do Responsável 1', max_length=200, null=True, verbose_name='Nome do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nome_responsavel_2',
            field=models.CharField(blank=True, help_text='Nome do Responsável 2', max_length=200, null=True, verbose_name='Nome do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nome_social',
            field=models.CharField(blank=True, help_text='Nome social', max_length=200, null=True, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='parentesco_responsavel_1',
            field=models.CharField(blank=True, help_text='Parentesco do Responsável 1', max_length=300, null=True, verbose_name='Parentesco do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='parentesco_responsavel_2',
            field=models.CharField(blank=True, help_text='Parentesco do Responsável 2', max_length=300, null=True, verbose_name='Parentesco do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='rg',
            field=models.CharField(blank=True, help_text='RG', max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='rg_orgao',
            field=models.CharField(blank=True, help_text='Orgão do RG', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='whatsapp_responsavel_1',
            field=models.CharField(blank=True, help_text='WhatsApp do Responsável 1', max_length=15, null=True, verbose_name='WhatsApp do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='whatsapp_responsavel_2',
            field=models.CharField(blank=True, help_text='WhatsApp do Responsável 1', max_length=15, null=True, verbose_name='WhatsApp do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, help_text='Nome do bairro', max_length=200, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular_responsavel_1',
            field=models.CharField(blank=True, help_text='Celular do Responsável 1', max_length=15, null=True, verbose_name='Celular do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular_responsavel_2',
            field=models.CharField(blank=True, help_text='Celular do Responsável 2', max_length=15, null=True, verbose_name='Celular do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=14, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento torre, sala etc', max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel_1',
            field=models.CharField(blank=True, help_text='CPF do Responsável 1', max_length=14, null=True, verbose_name='CPF do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel_2',
            field=models.CharField(blank=True, help_text='CPF do Responsável 1', max_length=14, null=True, verbose_name='CPF do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_responsavel_1',
            field=models.EmailField(blank=True, help_text='E-mail do Responsável 1', max_length=254, null=True, verbose_name='E-mail do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_responsavel_2',
            field=models.EmailField(blank=True, help_text='E-mail do Responsável 2', max_length=254, null=True, verbose_name='E-mail do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, help_text='Nome da rua, travessa ou avenida', max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[['+', '+'], ['-', '-']], help_text='Fator RH', max_length=8, null=True, verbose_name='Fator RH'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[['A', 'A'], ['B', 'B'], ['AB', 'AB'], ['O', 'O']], help_text='Grupo Sanguíneo', max_length=2, null=True, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=models.CharField(blank=True, help_text='Naturalidade', max_length=255, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Naturalidade', max_length=255, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, help_text='Nome da mãe', max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(blank=True, help_text='Nome do pai', max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_responsavel_1',
            field=models.CharField(blank=True, help_text='Nome do Responsável 1', max_length=200, null=True, verbose_name='Nome do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_responsavel_2',
            field=models.CharField(blank=True, help_text='Nome do Responsável 2', max_length=200, null=True, verbose_name='Nome do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_social',
            field=models.CharField(blank=True, help_text='Nome social', max_length=200, null=True, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco_responsavel_1',
            field=models.CharField(blank=True, help_text='Parentesco do Responsável 1', max_length=300, null=True, verbose_name='Parentesco do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco_responsavel_2',
            field=models.CharField(blank=True, help_text='Parentesco do Responsável 2', max_length=300, null=True, verbose_name='Parentesco do Responsável 2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, help_text='RG', max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg_orgao',
            field=models.CharField(blank=True, help_text='Orgão do RG', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='whatsapp_responsavel_1',
            field=models.CharField(blank=True, help_text='WhatsApp do Responsável 1', max_length=15, null=True, verbose_name='WhatsApp do Responsável 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='whatsapp_responsavel_2',
            field=models.CharField(blank=True, help_text='WhatsApp do Responsável 1', max_length=15, null=True, verbose_name='WhatsApp do Responsável 2'),
        ),
    ]
