# Generated by Django 4.2.10 on 2024-07-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0011_remove_procedimentoatendimento_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaorisco',
            name='escala_dor',
            field=models.SmallIntegerField(choices=[(0, 'LEVE'), (1, 'MODERADA'), (2, 'INTENSA'), (3, 'SEM DOR')], default=0, verbose_name='Escala de dor'),
        ),
        migrations.AlterField(
            model_name='historicalclassificacaorisco',
            name='escala_dor',
            field=models.SmallIntegerField(choices=[(0, 'LEVE'), (1, 'MODERADA'), (2, 'INTENSA'), (3, 'SEM DOR')], default=0, verbose_name='Escala de dor'),
        ),
        migrations.AlterField(
            model_name='preatendimentomedico',
            name='escala_dor',
            field=models.SmallIntegerField(choices=[(0, 'LEVE'), (1, 'MODERADA'), (2, 'INTENSA'), (3, 'SEM DOR')], default=0, verbose_name='Escala de cor'),
        ),
    ]
