# Generated by Django 4.2.10 on 2024-08-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0012_alter_classificacaorisco_escala_dor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaorisco',
            name='estado_geral',
            field=models.SmallIntegerField(choices=[(0, 'AGITAÇÃO'), (1, 'APARENTEMENTE BEM'), (2, 'CONSCIENTE'), (3, 'CONVULSÃO'), (4, 'DISPNEIA INTERNA'), (5, 'GRAVE'), (6, 'ORIENTADO'), (7, 'POLITRAUMATIZADO'), (8, 'PRECORDIALGIAS'), (9, 'REGULAR'), (10, 'SINAIS DE AGRAVAMENTO')], default=0, verbose_name='Estado geral'),
        ),
        migrations.AlterField(
            model_name='historicalclassificacaorisco',
            name='estado_geral',
            field=models.SmallIntegerField(choices=[(0, 'AGITAÇÃO'), (1, 'APARENTEMENTE BEM'), (2, 'CONSCIENTE'), (3, 'CONVULSÃO'), (4, 'DISPNEIA INTERNA'), (5, 'GRAVE'), (6, 'ORIENTADO'), (7, 'POLITRAUMATIZADO'), (8, 'PRECORDIALGIAS'), (9, 'REGULAR'), (10, 'SINAIS DE AGRAVAMENTO')], default=0, verbose_name='Estado geral'),
        ),
        migrations.AlterField(
            model_name='preatendimentomedico',
            name='estado_geral',
            field=models.SmallIntegerField(choices=[(0, 'AGITAÇÃO'), (1, 'APARENTEMENTE BEM'), (2, 'CONSCIENTE'), (3, 'CONVULSÃO'), (4, 'DISPNEIA INTERNA'), (5, 'GRAVE'), (6, 'ORIENTADO'), (7, 'POLITRAUMATIZADO'), (8, 'PRECORDIALGIAS'), (9, 'REGULAR'), (10, 'SINAIS DE AGRAVAMENTO')], default=0, verbose_name='Estado geral'),
        ),
    ]
