# Generated by Django 4.2.10 on 2024-09-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0013_alter_classificacaorisco_estado_geral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletimpaciente',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'URGÊNCIA'), (1, 'ADMINISTRAÇÃO MEDICAMENTO')], default=0, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalboletimpaciente',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'URGÊNCIA'), (1, 'ADMINISTRAÇÃO MEDICAMENTO')], default=0, verbose_name='Tipo'),
        ),
    ]
