# Generated by Django 4.2.10 on 2024-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0014_boletimpaciente_tipo_historicalboletimpaciente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exameatendimento',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'SOLICITADO'), (1, 'ANEXADO'), (2, 'SEM ANEXO'), (3, 'REABERTURA')], default=0, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='medicacaoatendimento',
            name='situacao',
            field=models.SmallIntegerField(choices=[(0, 'SOLICITADO'), (1, 'PARCIALMENTE APLICADO'), (2, 'SUSPENSO'), (3, 'CONCLUÍDO'), (4, 'REABERTURA')], default=0, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='procedimentoatendimento',
            name='situacao',
            field=models.SmallIntegerField(choices=[(0, 'SOLICITADO'), (1, 'SUSPENSO'), (2, 'CONCLUÍDO'), (3, 'REABERTURA')], default=0, verbose_name='Situação'),
        ),
    ]
