# Generated by Django 4.2.10 on 2024-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0015_alter_exameatendimento_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='situacao',
            field=models.CharField(choices=[['ATIVO', 'ATIVO'], ['INATIVO', 'INATIVO'], ['OBITO', 'ÓBITO']], default='ATIVO', max_length=7, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='situacao',
            field=models.CharField(choices=[['ATIVO', 'ATIVO'], ['INATIVO', 'INATIVO'], ['OBITO', 'ÓBITO']], default='ATIVO', max_length=7, verbose_name='Situação'),
        ),
    ]
