# Generated by Django 4.2.10 on 2024-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0016_alter_historicalpaciente_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaorisco',
            name='escala_dor',
            field=models.SmallIntegerField(choices=[(0, 'LEVE'), (1, 'MODERADA'), (2, 'INTENSA'), (3, 'SEM DOR')], verbose_name='Escala de dor'),
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='estado_geral',
            field=models.SmallIntegerField(choices=[(0, 'AGITAÇÃO'), (1, 'APARENTEMENTE BEM'), (2, 'CONSCIENTE'), (3, 'CONVULSÃO'), (4, 'DISPNEIA INTERNA'), (5, 'GRAVE'), (6, 'ORIENTADO'), (7, 'POLITRAUMATIZADO'), (8, 'PRECORDIALGIAS'), (9, 'REGULAR'), (10, 'SINAIS DE AGRAVAMENTO')], verbose_name='Estado geral'),
        ),
        migrations.AlterField(
            model_name='historicalclassificacaorisco',
            name='escala_dor',
            field=models.SmallIntegerField(choices=[(0, 'LEVE'), (1, 'MODERADA'), (2, 'INTENSA'), (3, 'SEM DOR')], verbose_name='Escala de dor'),
        ),
        migrations.AlterField(
            model_name='historicalclassificacaorisco',
            name='estado_geral',
            field=models.SmallIntegerField(choices=[(0, 'AGITAÇÃO'), (1, 'APARENTEMENTE BEM'), (2, 'CONSCIENTE'), (3, 'CONVULSÃO'), (4, 'DISPNEIA INTERNA'), (5, 'GRAVE'), (6, 'ORIENTADO'), (7, 'POLITRAUMATIZADO'), (8, 'PRECORDIALGIAS'), (9, 'REGULAR'), (10, 'SINAIS DE AGRAVAMENTO')], verbose_name='Estado geral'),
        ),
    ]
