# Generated by Django 4.2.10 on 2024-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0017_alter_classificacaorisco_escala_dor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallistachamada',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'EM ATENDIMENTO'), (2, 'EM PROCEDIMENTO'), (3, 'RETORNO'), (4, 'EM ATENDIMENTO DE RETORNO'), (5, 'ENCERRADO PELO ATENDIMENTO'), (6, 'ENCERRADO PELA ALTA'), (7, 'ENCERRADO PELA RECEPÇÃO'), (8, 'ENCERRADO PELO SISTEMA'), (9, 'LISTA DE RETORNO')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicoesperaatendimento',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'EM ATENDIMENTO'), (2, 'EM PROCEDIMENTO'), (3, 'RETORNO'), (4, 'EM ATENDIMENTO DE RETORNO'), (5, 'ENCERRADO PELO ATENDIMENTO'), (6, 'ENCERRADO PELA ALTA'), (7, 'ENCERRADO PELA RECEPÇÃO'), (8, 'ENCERRADO PELO SISTEMA'), (9, 'LISTA DE RETORNO')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='listachamada',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'EM ATENDIMENTO'), (2, 'EM PROCEDIMENTO'), (3, 'RETORNO'), (4, 'EM ATENDIMENTO DE RETORNO'), (5, 'ENCERRADO PELO ATENDIMENTO'), (6, 'ENCERRADO PELA ALTA'), (7, 'ENCERRADO PELA RECEPÇÃO'), (8, 'ENCERRADO PELO SISTEMA'), (9, 'LISTA DE RETORNO')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status'),
        ),
    ]
