# Generated by Django 4.2.10 on 2024-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0018_alter_historicallistachamada_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaorisco',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='historicalclassificacaorisco',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='preatendimentomedico',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Peso'),
        ),
    ]
