# Generated by Django 4.2.10 on 2025-02-07 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0005_alter_unidadesetor_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saude', '0008_unidadesaude_cep_unidadesaude_endereco'),
        ('saude_atendimento', '0019_alter_classificacaorisco_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacaoatendimento',
            name='estoque_zero',
            field=models.BooleanField(default=False, verbose_name='Confirmar com estoque zerado?'),
        ),
        migrations.CreateModel(
            name='ListaChamadaClassificacaoRisco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=1, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(choices=[(0, 'CHAMADO'), (1, 'EM ATENDIMENTO'), (2, 'CLASSIFICADO'), (3, 'CANCELADO')], default=0, verbose_name='Situação')),
                ('boletim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.boletimpaciente', verbose_name='Boletim do Paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': '2 - Lista de Espera da Classificação de Risco',
                'verbose_name_plural': '2 - Lista de Espera da Classificação de Risco',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalListaChamadaClassificacaoRisco',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('contagem', models.IntegerField(blank=True, default=1, null=True, verbose_name='Contagem')),
                ('situacao', models.SmallIntegerField(choices=[(0, 'CHAMADO'), (1, 'EM ATENDIMENTO'), (2, 'CLASSIFICADO'), (3, 'CANCELADO')], default=0, verbose_name='Situação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('boletim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_atendimento.boletimpaciente', verbose_name='Boletim do Paciente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.profissional')),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.sala')),
                ('unidade_saude', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'historical 2 - Lista de Espera da Classificação de Risco',
                'verbose_name_plural': 'historical 2 - Lista de Espera da Classificação de Risco',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
