# Generated by Django 4.2.10 on 2025-02-18 22:41

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import publicmanager.saude_atendimento.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0005_alter_unidadesetor_tipo'),
        ('saude_atendimento', '0021_alter_medicacaoatendimento_admin_medicamentosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoesperaatendimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional'),
        ),
        migrations.AlterField(
            model_name='historicallistachamada',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'EM ATENDIMENTO'), (2, 'EM PROCEDIMENTO'), (3, 'RETORNO'), (4, 'EM ATENDIMENTO DE RETORNO'), (5, 'ENCERRADO PELO ATENDIMENTO'), (6, 'ENCERRADO PELA ALTA'), (7, 'ENCERRADO PELA RECEPÇÃO'), (8, 'ENCERRADO PELO SISTEMA'), (9, 'LISTA DE RETORNO'), (10, 'ATENDIMENTO REABERTO')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicoesperaatendimento',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'EM ATENDIMENTO'), (2, 'EM PROCEDIMENTO'), (3, 'RETORNO'), (4, 'EM ATENDIMENTO DE RETORNO'), (5, 'ENCERRADO PELO ATENDIMENTO'), (6, 'ENCERRADO PELA ALTA'), (7, 'ENCERRADO PELA RECEPÇÃO'), (8, 'ENCERRADO PELO SISTEMA'), (9, 'LISTA DE RETORNO'), (10, 'ATENDIMENTO REABERTO')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='listachamada',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'EM ESPERA'), (1, 'EM ATENDIMENTO'), (2, 'EM PROCEDIMENTO'), (3, 'RETORNO'), (4, 'EM ATENDIMENTO DE RETORNO'), (5, 'ENCERRADO PELO ATENDIMENTO'), (6, 'ENCERRADO PELA ALTA'), (7, 'ENCERRADO PELA RECEPÇÃO'), (8, 'ENCERRADO PELO SISTEMA'), (9, 'LISTA DE RETORNO'), (10, 'ATENDIMENTO REABERTO')], default=0, help_text='situação Atual do Chamado', null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ReaberturaAtendimentoMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('justificativa', models.TextField(verbose_name='justificativa')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_atendimento.atendimentomedico')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional')),
            ],
            options={
                'verbose_name': 'Reabertura Atendimento Médico',
                'verbose_name_plural': '4 - Reaberturas Atendimento Médico',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArquivoExameAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=publicmanager.saude_atendimento.models.exame_atendimento_anexo_path, verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('exame_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='saude_atendimento.exameatendimento')),
            ],
            options={
                'verbose_name': 'Arquivo de Exame Atendimento',
                'verbose_name_plural': 'Arquivos de Exame Atendimento',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
