# Generated by Django 4.2.10 on 2025-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0022_historicoesperaatendimento_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular', max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='E-mail', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='telefone_fixo',
            field=models.CharField(blank=True, db_index=True, help_text='Telefone Fixo', max_length=14, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='whatsapp',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp', max_length=15, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular', max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail', max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_fixo',
            field=models.CharField(blank=True, help_text='Telefone Fixo', max_length=14, null=True, unique=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp', max_length=15, null=True, unique=True, verbose_name='WhatsApp'),
        ),
    ]
