# Generated by Django 4.2.10 on 2025-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0023_alter_historicalpaciente_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentoatendimento',
            name='realizado_por',
            field=models.SmallIntegerField(choices=[(0, 'ENFERMAGEM'), (1, 'MÉDICO')], default=0, verbose_name='Realizado por'),
        ),
    ]
