# Generated by Django 4.2.10 on 2025-02-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0024_procedimentoatendimento_realizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaorisco',
            name='tipo_fluxo',
            field=models.SmallIntegerField(choices=[(0, 'URGÊNCIA'), (1, 'PROCEDIMENTOS ELETIVO')], default=0, verbose_name='Tipo Fluxo'),
        ),
        migrations.AddField(
            model_name='historicalclassificacaorisco',
            name='tipo_fluxo',
            field=models.SmallIntegerField(choices=[(0, 'URGÊNCIA'), (1, 'PROCEDIMENTOS ELETIVO')], default=0, verbose_name='Tipo Fluxo'),
        ),
    ]
