# Generated by Django 4.2.10 on 2025-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0025_classificacaorisco_tipo_fluxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacaoatendimento',
            name='medicamento_controlado',
            field=models.BooleanField(default=False, verbose_name='Medicamento Controlado?'),
        ),
    ]
