# Generated by Django 4.2.10 on 2025-03-05 18:56

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import publicmanager.saude_atendimento.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude_atendimento', '0026_medicacaoatendimento_medicamento_controlado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoProcedimentoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=publicmanager.saude_atendimento.models.procedimento_atendimento_anexo_path, verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('procedimento_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='saude_atendimento.procedimentoatendimento')),
            ],
            options={
                'verbose_name': 'Arquivo de Procedimento Atendimento',
                'verbose_name_plural': 'Arquivos de Procedimento Atendimento',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
