# Generated by Django 4.2.10 on 2024-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='tipo_profissional',
            field=models.SmallIntegerField(choices=[(0, 'DESENVOLVEDOR'), (1, 'RECEPCIONISTA'), (2, 'MÉDICO'), (3, 'ENFERMEIRO(A)'), (4, 'RADIOLOGISTA'), (5, 'FARMACÊUTICO'), (6, 'TERAPEUTA'), (7, 'NUTRICIONISTA'), (8, 'ADMINISTRADO'), (9, 'SUPORTE'), (10, 'TECNICO DE ENFERMAGEM')]),
        ),
    ]
