# Generated by Django 4.2.10 on 2024-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0002_alter_profissional_tipo_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cofen',
            field=models.CharField(blank=True, help_text='COFEN', max_length=7, verbose_name='COFEN'),
        ),
    ]
