# Generated by Django 4.2.10 on 2024-12-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0003_profissional_cofen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='recepcao_noturno',
            field=models.BooleanField(default=False, verbose_name='Faz admissão noturna de pacientes?'),
        ),
    ]
