# Generated by Django 4.2.10 on 2025-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_cadastro', '0004_profissional_recepcao_noturno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesetor',
            name='tipo',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'RECEPÇÃO'), (1, 'URGÊNCIA'), (2, 'CONSULTÓRIO'), (3, 'ENFERMARIA'), (4, 'INTERNAÇÃO'), (5, 'FARMACIA'), (6, 'NUTRIÇÃO'), (7, 'LABORATÓRIO'), (8, 'CENTRO CIRÚRGICO'), (9, 'MATERNIDADE'), (10, 'OBSTRETICIA'), (11, 'PEDIATRIA'), (12, 'RADIOLOGIA'), (13, 'RH'), (14, 'ADMINISTRATIVO'), (15, 'CLASSIFICAÇÃO DE RISCO')], null=True, verbose_name='Tipo'),
        ),
    ]
