# Generated by Django 4.2.10 on 2024-05-06 01:12

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import simple_history.models
import smart_selects.db_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUnidadeLogin',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Unidade logado',
                'verbose_name_plural': 'historical Unidades Logado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResponsavelUnidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Responsavel da Unidade',
                'verbose_name_plural': 'Responsaveis das Unidades',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnidadeLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Unidade logado',
                'verbose_name_plural': 'Unidades Logado',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, verbose_name='Email do responsável')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone do responsável')),
                ('situacao', models.SmallIntegerField(choices=[(0, 'Ativo'), (1, 'Desativado')], default=0, verbose_name='Situação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('alta_atendimento', models.BooleanField(default=False, verbose_name='Faz alta no atendimento?')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla da unidade')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('tipo_unidade', models.SmallIntegerField(choices=[(0, 'GEAL'), (1, 'URGENCIA'), (2, 'CONSULTORIO')], default=0, verbose_name='Tipo Unidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.estado')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.PROTECT, to='comum.municipio')),
            ],
            options={
                'verbose_name': 'Unidade de Saúde',
                'verbose_name_plural': 'Unidades de Saúde',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
