# Generated by Django 4.2.10 on 2024-05-06 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saude', '0001_initial'),
        ('saude_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadelogin',
            name='profissional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional'),
        ),
        migrations.AddField(
            model_name='unidadelogin',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.sala'),
        ),
        migrations.AddField(
            model_name='unidadelogin',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude'),
        ),
        migrations.AddField(
            model_name='responsavelunidade',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude_cadastro.profissional', verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='responsavelunidade',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude.unidadesaude', verbose_name='Unidade de Saúde'),
        ),
        migrations.AddField(
            model_name='historicalunidadelogin',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalunidadelogin',
            name='profissional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.profissional'),
        ),
        migrations.AddField(
            model_name='historicalunidadelogin',
            name='sala',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude_cadastro.sala'),
        ),
        migrations.AddField(
            model_name='historicalunidadelogin',
            name='unidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='saude.unidadesaude'),
        ),
    ]
