# Generated by Django 4.2.10 on 2024-05-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesaude',
            name='tipo_unidade',
            field=models.SmallIntegerField(choices=[(0, 'GERAL'), (1, 'URGENCIA'), (2, 'CONSULTORIO')], default=0, verbose_name='Tipo Unidade'),
        ),
    ]
