# Generated by Django 4.2.10 on 2024-05-13 16:38

from django.db import migrations, models
import django_lifecycle.mixins
import publicmanager.saude.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_alter_unidadesaude_tipo_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=publicmanager.saude.models.manual_path, verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.SmallIntegerField(choices=[(0, 'DESENVOLVEDOR'), (1, 'RECEPCIONISTA'), (2, 'MÉDICO'), (3, 'ENFERMEIRO(A)'), (4, 'RADIOLOGISTA'), (5, 'FARMACÊUTICO'), (6, 'TERAPEUTA'), (7, 'NUTRICIONISTA'), (8, 'ADMINISTRADO'), (9, 'SUPORTE')])),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuais',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
