# Generated by Django 4.2.10 on 2024-05-14 14:02

from django.db import migrations, models
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsqueceuSenha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(max_length=255)),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
            ],
            options={
                'verbose_name': 'Esqueceu Senha',
                'verbose_name_plural': 'Esqueceu Senhas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
