# Generated by Django 4.2.10 on 2024-05-23 15:34

from django.db import migrations, models
import publicmanager.saude.models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0005_esqueceusenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='logo',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to=publicmanager.saude.models.logo_upload_to, verbose_name='Imagem'),
        ),
    ]
